services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ges_emp'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
    volumes:
      - pgvector-data:/var/lib/postgresql/data
volumes:
  pgvector-data: